feat: Add JWT external signature method (TEE) and JWK thumbprint [SIW-283,297]
pagopa/io-react-native-jwt pull request #6
Opened 2023-07-17 15:46 UTC by grausof

## Short description
The method for adding the signature via `TEE` is fixed and the calculation of the `JWK` thumbprint is also added.

## List of changes proposed in this pull request
- Added [io-react-native-crypto](https://github.com/pagopa/io-react-native-crypto) integration in example app.
- Added conversion from `ASN.1 BER` encoded to plain signature. Refs: [stackExchange](https://crypto.stackexchange.com/questions/1795/how-can-i-convert-a-der-ecdsa-signature-to-asn-1)
- Added `JWK` thumbprint calculation
- Added `RSA` signing support
- Added verification of signature algorithms
- Added proxy to skip `react-native` integration during test

## How to test
Unit-test and test on real device!

2023-07-17 16:36 UTC, hevelius requested changes

2023-07-17 16:36 UTC, hevelius commented on src/__tests__/sign.test.ts
> +    let signedJwt = await SignJWT.appendAsn1Signature(toSign, signature);
```suggestion
    const signedJwt = await SignJWT.appendAsn1Signature(toSign, signature);
```

2023-07-17 16:36 UTC, hevelius commented on src/sign.ts
> +    let protectedHeader = encodeBase64(JSON.stringify(this._protectedHeader));
```suggestion
    const protectedHeader = encodeBase64(JSON.stringify(this._protectedHeader));
```

2023-07-17 16:36 UTC, hevelius commented on src/sign.ts
> +    let payload = encodeBase64(JSON.stringify(this._payload));
```suggestion
    const payload = encodeBase64(JSON.stringify(this._payload));
```

2023-07-17 16:36 UTC, hevelius commented on src/sign.ts
> +    let jwtDecoded = SignJWT.decodeJwtWithoutSignature(jwtWithoutSignature);
```suggestion
    const jwtDecoded = SignJWT.decodeJwtWithoutSignature(jwtWithoutSignature);
```

2023-07-17 16:36 UTC, hevelius commented on src/sign.ts
> +    let alg = jwtDecoded.header.alg;
```suggestion
    const alg = jwtDecoded.header.alg;
```

2023-07-17 16:36 UTC, hevelius commented on src/utils/asn1.ts
> + * Returna a base64 url encoded String.
```suggestion
 * Returns a base64 url encoded String.
```

2023-07-17 16:36 UTC, hevelius commented on src/utils/asn1.ts
> +  let kty = getKtyFromAlg(alg);
```suggestion
  const kty = getKtyFromAlg(alg);
```

2023-07-17 16:36 UTC, hevelius commented on src/utils/asn1.ts
> +    );
```suggestion
    const unpackedJws = await IoReactNativeJwt.unpackBerEncodedASN1(
      asn1Signature,
      getCoordinateOctetLength(alg)
    );
```

2023-07-17 16:36 UTC, hevelius commented on README.md
Perhaps it could be useful to add a description of what was found with the TEE and ASIN.1... Btw I don't have a strong opinion on this though.

2023-07-18 06:47 UTC, hevelius approved these changes
LGTM

2023-07-18 06:54 UTC, grausof commented on README.md
I've added some references and an explanation in the README. Also I pointed out that this format is only valid for ECDSA

2023-07-18 07:01 UTC, merged